#!/bin/sh

. "${CLASH_ROOT-.}"/test/testlib/assert || exit

log="${CLASH_ROOT-.}"/test/run.log

: > "$log"
while IFS= read -r shell; do
  while IFS= read -r test; do
    export TIME="Time: $shell,$test,%e"
    OLDIFS="$IFS"
    IFS=' '
    set -- $shell ${errexit+-e}
    printf '%s %s - ' "$*" "$test"
    IFS="$OLDIFS"
    if assert_true time "$@" "${CLASH_ROOT-.}/test/$test" -- "$shell failed $test" >> "$log" 2>&1
    then
      printf '\033[1;32mOK\033[0m\n'
    else
      printf '\033[1;31mKO\033[0m\n'
    fi
  done < "${CLASH_ROOT-.}"/test/tests.txt
  echo
done < "${CLASH_ROOT-.}"/test/shells.txt

end_tests && {
  date
  printf commit:; git rev-parse HEAD
  sed -n 's/^Time: \(.*\)/\1/p' "$log"
} >> "${CLASH_ROOT-.}"/test/runtime.txt
