#!/bin/sh

if ! [ -f ./clash ]; then
  echo 'Could not locate clash'
  exit 1
fi >&2

. ./clash
. ./lib/list

dummy_hash() {
  str="$1"
  hash_value=0
  while [ -n "$str" ]; do
    tmp="$str"
    str="${str#?}"
    char="${tmp%$str}"
    char_num="$(printf %d "'$char")"
    hash_value="$((hash_value + char_num))"
  done
  printf '%s\n' "$((hash_value % 8))"
}

class Dict_Tuple \
  key            \
  value          \
  _print         \

Dict_Tuple_print() {
  printf '('
  if ! "$key"_print 2> /dev/null; then
    printf '%s' "$key"
  fi
  printf ', '
  if ! "$value"_print 2> /dev/null; then
    printf '%s' "$value"
  fi
  printf ')'
}

class Dict       \
  hash_function  \
  buckets_       \
  _clear         \
  _get           \
  _keys          \
  _length        \
  _pop           \
  _pretty_print  \
  _set           \
  _values        \

Dict_get() {
  local hash_value="$("$hash_function" "$1")"
  local tuple
  if tuple_list="$("$self"_node_"$hash_value"_tuple_list_value 2> /dev/null)" &&
    tuple="$(
      matching_tuple() {
        [ "$("$2"_key; printf x)" = "$1"x ]
      }
      "$tuple_list"_find matching_tuple "$1"
    )"
  then
    local value="$("$tuple"_value; printf x)"
    printf %s "${value%x}"
  else
    printf 'Key not found: %s\n' "$1" >&2
  fi
}

Dict_pretty_print() {
  printf '== %s == (nb buckets: %s)\n' "$self" "$("$buckets_"_length_)"

  (
    tuple_printer() {
      printf '%s -> ' "$1"
      "$1"_print
    }
    "$buckets_"_foreach tuple_printer
  )
}

Dict_set() {
  local hash_value="$("$hash_function" "$1")"
  local node="$self"_node_"$hash_value" # 3 types tuple_list/{key,value}_$tuple_length
  local tuple_id="$(Dict_Tuple_id)"
  Dict_Tuple "$tuple_id" "$1" "$2"
  if tuple_list="$("$node"_tuple_list_value 2> /dev/null)"; then
    "$tuple_list"_append "$tuple_id"
  else
    local list_id="$(List_id)"
    List "$list_id" "$tuple_id"
    List_node "$node"_tuple_list "$list_id"
    "$buckets_"_append_node_ "$node"_tuple_list
  fi
}

_Dict() {
  local list_id="$(List_id)"
  List "$list_id"
  "$self"_buckets__is "$list_id"
  "$self"_hash_function_is dummy_hash
}
