#!/bin/sh

# shebang for coloration, this should only be sourced

if ! [ -f "${CLASH_ROOT-.}"/clash ]; then
  echo 'Could not locate clash'
  exit 1
fi >&2

. "${CLASH_ROOT-.}"/lib/list || exit

# for each char: get ascii value, sum them all, and modulo 8 the total
dummy_hash() {
  local str="$1"
  local hash_value=0
  local tmp=
  local char=
  local char_num=
  while [ -n "$str" ]; do
    tmp="$str"
    str="${str#?}"
    char="${tmp%$str}"
    char_num="$(printf %d "'$char")" # supported by osh >= 0.7.pre6
    hash_value="$((hash_value + char_num))"
  done
  printf '%s\n' "$((hash_value % 8))"
}

class Dict_tuple \
  key            \
  value          \
  _print         \

Dict_tuple_print() {
  printf '('
  if command -v "$key"_print > /dev/null; then
    "$key"_print
  else
    printf '%s' "$key"
  fi
  printf ', '
  if command -v "$value"_print > /dev/null; then
    "$value"_print
  else
    printf '%s' "$value"
  fi
  printf ')'
}

# Any decent hash function written in shell will be far from fast, we'll keep
# this structure to avoid recomputing the hash function if 2 successive lookups
# are done. This basically just keeps the last key/hash computation.
# This effectively means that we consider the hashing function to be slower
# than spawning a few subshells, which might depend on the shell in use.
class Dict_hash_cache \
  stale               \
  key                 \
  hash                \

class Dict       \
  hash_function  \
  length         \
  buckets_       \
  last_hashed_   \
  _clear         \
  _get           \
  _items         \
  _pretty_print  \
  _remove        \
  _set           \
  __del__        \
  __init__       \

Dict_clear() {
  "$buckets_"_foreach Dict_clean_bucket
  "$buckets_"_clear
  "$self"_length_is 0
  "$last_hashed_"_stale_is true
}

Dict_get() {
  if ! "$("$last_hashed_"_stale)" &&
     [ "$("$last_hashed_"_key; printf x)" = "$1"x ]; then
    local hash_value="$("$last_hashed_"_hash)"
  else
    local hash_value="$("$hash_function" "$1")"
    "$last_hashed_"_key_is "$1"
    "$last_hashed_"_hash_is "$hash_value"
    "$last_hashed_"_stale_is false
  fi

  local node="$self"_node_"$hash_value"
  local tuple_list=
  local tuple=
  if command -v "$node"_tuple_list_value > /dev/null && # matching bucket?
    tuple_list="$("$node"_tuple_list_value)" &&
    tuple="$("$tuple_list"_find Dict_matching_tuple "$1")" # matching tuple?
  then
    local value="$("$tuple"_value; printf x)"
    printf %s "${value%x}"
  else
    printf 'Key not found: %s\n' "$1" >&2
    return 1
  fi
}

Dict_items() {
  List "$1"
  "$buckets_"_foreach "$1"_concat
}

Dict_pretty_print() {
  printf '== %s == (nb buckets: %s)\n' "$self" "$("$buckets_"_length)"

  (
    tuple_printer() {
      printf '%s -> ' "$1"
      "$1"_print
    }
    "$buckets_"_foreach tuple_printer
  )
}

Dict_remove() {
  if ! "$("$last_hashed_"_stale)" &&
     [ "$("$last_hashed_"_key; printf x)" = "$1"x ]; then
    local hash_value="$("$last_hashed_"_hash)"
  else
    local hash_value="$("$hash_function" "$1")"
    "$last_hashed_"_key_is "$1"
    "$last_hashed_"_hash_is "$hash_value"
    "$last_hashed_"_stale_is false
  fi
  local node="$self"_node_"$hash_value"
  local tuple_list=
  if command -v "$node"_tuple_list_value > /dev/null && # matching bucket?
    tuple_list="$("$node"_tuple_list_value)" &&
    "$tuple_list"_remove_if Dict_matching_tuple "$1" # removed tuple?
  then
    "$self"_length_is "$((length - 1))"
    if "$tuple_list"_is_empty; then
      del "$tuple_list"
      "$buckets_"_remove_node_ "$node"_tuple_list
    fi
  else
    printf 'Key not found: %s\n' "$1" >&2
    return 1
  fi
}

Dict_set() {
  if [ "$("$self"_get "$1" 2> /dev/null; printf x)" = "$2"x ]; then
    return 0 # key/value pair already in the dict
  fi
  # _get call right above should have populated the hash cache
  if ! "$("$last_hashed_"_stale)" &&
     [ "$("$last_hashed_"_key; printf x)" = "$1"x ]; then
    local hash_value="$("$last_hashed_"_hash)"
  else
    local hash_value="$("$hash_function" "$1")"
    "$last_hashed_"_key_is "$1"
    "$last_hashed_"_hash_is "$hash_value"
    "$last_hashed_"_stale_is false
  fi
  local node="$self"_node_"$hash_value" # 3 types tuple_list/{key,value}_$tuple_length
  local tuple_id="$(Dict_tuple_anonymous_id)"
  Dict_tuple "$tuple_id" "$1" "$2"
  "$self"_length_is "$((length + 1))"
  if command -v "$node"_tuple_list_value > /dev/null; then # matching bucket?
    "$("$node"_tuple_list_value)"_append "$tuple_id"
  else
    local list_id="$(List_anonymous_id)"
    List "$list_id" "$tuple_id" # create new bucket containing the new tuple
    List_node "$node"_tuple_list "$list_id" # create bucket list node
    "$buckets_"_append_node_ "$node"_tuple_list
  fi
}

Dict__del__() {
  "$self"_clear
  del "$buckets_"
  del "$last_hashed_"
}

Dict__init__() {
  local hash_cache_id="$(Dict_hash_cache_anonymous_id)"
  Dict_hash_cache "$hash_cache_id" true # set cached initially as stale
  "$self"_last_hashed__is "$hash_cache_id"
  local list_id="$(List_anonymous_id)"
  List "$list_id"
  "$self"_buckets__is "$list_id"
  "$self"_hash_function_is dummy_hash
  "$self"_length_is 0
}

# "Static" methods

Dict_matching_tuple() {
  [ "$("$2"_key; printf x)" = "$1"x ]
}

# Cannot be create and applied in a subshell since we modify our global state
Dict_clean_bucket() {
  "$1"_foreach del # since tuples are only references we need to delete them
  del "$1" # delete bucket
}
