#!/bin/sh

# shebang for coloration, this should only be sourced

if ! [ -f "${CLASH_ROOT-.}"/clash ]; then
  echo 'Could not locate clash'
  exit 1
fi >&2

class Vector_node \
  value           \

class Vector     \
  length         \
  _append        \
  _clear         \
  _clone         \
  _concat        \
  _filter        \
  _find          \
  _foreach       \
  _get           \
  _index         \
  _insert        \
  _is_empty      \
  _map           \
  _pop           \
  _pretty_print  \
  _print         \
  _reduce        \
  _remove        \
  _remove_if     \
  _set           \
  _new_node_     \
  _shift_left_   \
  _shift_right_  \
  __del__        \
  __init__       \

check_index_within_range() {
  # 1 -> index
  # 2 -> length
  if [ -z "$1" ] ||
     [ "$1" -ge "$2" ] ||
     [ "$1" -le -"$2" ]
  then
    printf 'Invalid index: %s\n' "$1"
    return 1
  fi >&2
}

get_positive_index() {
  if [ "$1" -lt 0 ]; then
    printf %s "$((length + $1))"
  else
    printf %s "${1#-}" # remove - sign from -0
  fi
}

Vector_append() {
  local value=
  for value do
    "$self"_new_node_ "$value"
  done
}

Vector_clear() {
  local index=0
  while [ "$index" -lt "$length" ]; do
    del "$self"_Vector_node_"$index"
    index="$((index + 1))"
  done
  "$self"_length_is 0
}

Vector_clone() {
  Vector "$1"
  "$self"_foreach "$1"_append
}

Vector_concat() {
  for vector do
    "$vector"_foreach "$self"_append
  done
}

Vector_filter() {
  local new_vector="$1"
  shift
  Vector "$new_vector"
  local index=0
  local node_value=
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    if "$@" "$node_value"; then
      "$new_vector"_append "$node_value"
    fi
    index="$((index + 1))"
  done
}

# Find a value matching a given predicate
Vector_find() {
  local index=0
  local node_value=
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    if "$@" "$node_value"; then
      printf %s "$node_value"
      return 0
    fi
    index="$((index + 1))"
  done
  return 1
}

Vector_foreach() {
  local index=0
  local node_value=
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    "$@" "$node_value"
    index="$((index + 1))"
  done
}

Vector_get() {
  check_index_within_range "$1" "$length" || return
  local target_index="$(get_positive_index "$1")"
  local value="$("$self"_Vector_node_"$target_index"_value; printf x)"
  value="${value%x}"
  printf %s "$value"
}

Vector_index() {
  local index=0
  local value=
  while [ "$index" -lt "$length" ]; do
    if [ "$("$self"_Vector_node_"$index"_value; printf x)" = "$1"x ]; then
      printf %s "$index"
      return 0
    fi
    index="$((index + 1))"
  done
  printf 'Value not found: %s\n' "$1" >&2
  return 1
}

Vector_insert() {
  check_index_within_range "$1" "$((length + 1))" || return
  local target_index="$(get_positive_index "$1")"
  "$self"_shift_right_ "$target_index"
  "$self"_Vector_node_"$target_index"_value_is "$2"
}

Vector_is_empty() {
  [ "$length" -eq 0 ]
}

Vector_map() {
  local new_vector="$1"
  shift
  Vector "$new_vector"
  local index=0
  local node_value=
  local new_value=
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    new_value="$("$@" "$node_value"; printf x)"
    new_value="${new_value%x}"
    "$new_vector"_append "$new_value"
    index="$((index + 1))"
  done
}

Vector_pop() {
  set -- "${1-0}"
  check_index_within_range "$1" "$length" || return
  local target_index="$(get_positive_index "$1")"
  local value="$("$self"_Vector_node_"$target_index"_value; printf x)"
  value="${value%x}"
  "$self"_shift_left_ "$target_index"
  printf %s "$value"
}

Vector_pretty_print() {
  printf '== %s == (length: %s)\n' "$self" "$length"
  local index=0
  local value=
  while [ "$index" -lt "$length" ]; do
    value="$("$self"_Vector_node_"$index"_value; printf x)"
    value="${value%x}"
    printf '%s: %s\n' "$index" "$value"
    index="$((index + 1))"
  done
}

Vector_print() {
  (
    node_printer() {
      # let's assume there's no binary called $1_print that could cause a false
      # positive, otherwise we could verify the output of command -v which
      # should be exactly "$1"_print (or just unset PATH)
      if command -v "$1"_print > /dev/null; then
        "$1"_print
      else
        printf '%s' "$1"
      fi
      local delim=
      if [ -z "${IFS+x}" ]; then
        delim=' ' # space delimiter if IFS is unset
      elif [ -n "$IFS" ]; then
        local tmp="${IFS#?}"
        delim="${IFS%$tmp}" # IFS first char is the print delim, like "$*"
      fi
      printf %s "$delim"
    }
    "$self"_foreach node_printer
  )
  echo
}

Vector_reduce() {
  if "$self"_is_empty; then
    printf '%s is empty, nothing to reduce\n' "$self"
    return 1
  fi >&2

  local node_value="$("$self"_Vector_node_0_value; printf x)"
  local accumulated_value="${node_value%x}"
  local index=1
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    accumulated_value="$("$@" "$accumulated_value" "$node_value"; printf x)"
    accumulated_value="${accumulated_value%x}"
    index="$((index + 1))"
  done
  printf %s "$accumulated_value"
}

Vector_remove() {
  if ! "$self"_remove_if test "$1" =; then
    printf 'Value not found: %s\n' "$1" >&2
    return 1
  fi
}

Vector_remove_if() {
  local index=0
  local node_value=
  while [ "$index" -lt "$length" ]; do
    node_value="$("$self"_Vector_node_"$index"_value; printf x)"
    node_value="${node_value%x}"
    if "$@" "$node_value"; then
      "$self"_shift_left_ "$index"
      return 0
    fi
    index="$((index + 1))"
  done
  return 1
}

Vector_set() {
  check_index_within_range "$1" "$length" || return
  local target_index="$(get_positive_index "$1")"
  local value="$("$self"_Vector_node_"$target_index"_value; printf x)"
  "$self"_Vector_node_"$target_index"_value_is "$2"
}

Vector_new_node_() {
  local node_name="$self"_Vector_node_"$length"
  Vector_node "$node_name" "$1"
  "$self"_length_is "$((length + 1))"
}

Vector_shift_left_() {
  local index="$(($1 + 1))"
  local value=
  while [ "$index" -lt "$length" ]; do
    value="$("$self"_Vector_node_"$index"_value; printf x)"
    "$self"_Vector_node_"$((index - 1))"_value_is "${value%x}"
    index="$((index + 1))"
  done
  "$self"_length_is "$((length - 1))"
  del "$self"_Vector_node_"$("$self"_length)"
}

Vector_shift_right_() {
  local index="$((length - 1))"
  local target_index="$1"
  local value=
  "$self"_append ''
  while [ "$index" -ge "$target_index" ]; do
    value="$("$self"_Vector_node_"$index"_value; printf x)"
    "$self"_Vector_node_"$((index + 1))"_value_is "${value%x}"
    index="$((index - 1))"
  done
}

Vector__del__() {
  "$self"_clear
}

Vector__init__() {
  "$self"_length_is 0
  "$self"_append "$@"
}
