#!/bin/sh

. "${CLASH_ROOT-.}"/test/testlib/assert || exit

. "${CLASH_ROOT-.}"/clash || exit

. "${CLASH_ROOT-.}"/lib/set || exit

Set s 0 8 -8 4 12 10 11 5 7 9 20 30 9

s_print

print_dot "$(s_root_)" > /tmp/graph.gv
dot -Tpng /tmp/graph.gv -o /tmp/graph.png
feh /tmp/graph.png
