#!/bin/sh

condition()
{
  nb_args="$#"
  set -- "$@" "$@"
  index=0
  while [ "$index" -lt "$nb_args" ]; do
    [ "$1" = '--' ] && separator_index="$index"
    index="$((index + 1))"
    shift
  done
  index=0
  while [ "$index" != "$separator_index" ]; do
    set -- "$@" "$1"
    index="$((index + 1))"
    shift
  done
  shift "$(($# - separator_index))"
  "$@"
}

assert() {
  condition "$@" > /dev/null 2>&1
  if [ "$?" "$assert_operator" 0 ]; then
    return
  fi

  shift "$((separator_index + 1))"
  {
    if [ -t 2 ]; then
      printf '\033[1;31mError\033[0m - '
    else
      printf 'Error - '
    fi
    printf "$@"
    echo
  } >&2
  exit 1
}

assert_true() {
  printf '%s -> true\n' "$*"
  assert_operator='='
  assert "$@"
}

assert_false() {
  printf '%s -> false\n' "$*"
  assert_operator='!='
  assert "$@"
}

assert_out() {
  printf '%s\n' "$*"
  out_file="$(mktemp)"
  condition "$@" > "$out_file" 2> /dev/null
  shift "$((separator_index + 1))"
  output="$(cat "$out_file"; printf x)"
  output="${output%x}"
  assert_operator='='
  assert [ "$output" = "$*" ] -- 'Output differ:
--- expected ---
%s
---- actual ----
%s
----------------' "$*" "$output"
  rm "$out_file"
}
